import type { ShopItem } from '../models/decoration';

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'sticker-sun',
    name: '햇살',
    description: '따뜻한 하루',
    category: 'sticker',
    slot: 'diarySticker',
    price: 0,
    symbol: '☀️',
    color: '#FFF3BF',
    isDefault: true,
  },
  {
    id: 'sticker-clover',
    name: '클로버',
    description: '작은 행운',
    category: 'sticker',
    slot: 'diarySticker',
    price: 0,
    symbol: '🍀',
    color: '#DFF7DF',
    isDefault: true,
  },
  {
    id: 'sticker-heart',
    name: '포근한 마음',
    description: '오늘을 다독여요',
    category: 'sticker',
    slot: 'diarySticker',
    price: 0,
    symbol: '🤎',
    color: '#F4E3D7',
    isDefault: true,
  },
  {
    id: 'sticker-coffee',
    name: '커피 한 잔',
    description: '잠깐의 여유',
    category: 'sticker',
    slot: 'diarySticker',
    price: 30,
    symbol: '☕',
    color: '#E8D5C4',
  },
  {
    id: 'sticker-book',
    name: '읽는 시간',
    description: '조용한 한 페이지',
    category: 'sticker',
    slot: 'diarySticker',
    price: 40,
    symbol: '📖',
    color: '#DDE8F5',
  },
  {
    id: 'sticker-flower',
    name: '들꽃',
    description: '천천히 피어나요',
    category: 'sticker',
    slot: 'diarySticker',
    price: 50,
    symbol: '🌼',
    color: '#FFF0C7',
  },
  {
    id: 'tape-linen',
    name: '린넨 테이프',
    description: '포근한 베이지',
    category: 'tape',
    slot: 'diaryTape',
    price: 0,
    symbol: '▰',
    color: '#E8D8C4',
    isDefault: true,
  },
  {
    id: 'tape-forest',
    name: '숲빛 테이프',
    description: '차분한 초록',
    category: 'tape',
    slot: 'diaryTape',
    price: 120,
    symbol: '▰',
    color: '#AFC8A5',
  },
  {
    id: 'tape-sky',
    name: '하늘 테이프',
    description: '맑은 파랑',
    category: 'tape',
    slot: 'diaryTape',
    price: 150,
    symbol: '▰',
    color: '#AFCDE8',
  },
  {
    id: 'cover-cream',
    name: '크림 일기장',
    description: '기본 포근한 표지',
    category: 'cover',
    slot: 'diaryCover',
    price: 0,
    symbol: '📔',
    color: '#EEDFC8',
    isDefault: true,
  },
  {
    id: 'cover-forest',
    name: '숲 일기장',
    description: '초록빛 천 표지',
    category: 'cover',
    slot: 'diaryCover',
    price: 300,
    symbol: '📗',
    color: '#91A98C',
  },
  {
    id: 'cover-night',
    name: '밤 일기장',
    description: '고요한 남색 표지',
    category: 'cover',
    slot: 'diaryCover',
    price: 450,
    symbol: '📘',
    color: '#6F7C98',
  },
  {
    id: 'bed-basic',
    name: '포근한 침대',
    description: '크림 이불과 세이지 담요',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 0,
    symbol: '🛏️',
    color: '#DCC79F',
    isDefault: true,
    gridSize: { columns: 4, rows: 2 },
  },
  {
    id: 'desk-basic',
    name: '나무 책상',
    description: '창가의 기본 책상',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 0,
    symbol: '🖥️',
    color: '#B98A62',
    isDefault: true,
    gridSize: { columns: 3, rows: 2 },
  },
  {
    id: 'bed-mint',
    name: '민트 침대',
    description: '산뜻한 민트빛 침구',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 420,
    symbol: '🛏️',
    color: '#BFDCD3',
  },
  {
    id: 'desk-cream',
    name: '크림 책상',
    description: '밝고 단정한 책상',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 360,
    symbol: '🖥️',
    color: '#EAD9B8',
  },
  {
    id: 'desk-walnut-drawers',
    name: '월넛 서랍 책상',
    description: '짙은 원목과 황동 손잡이',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 520,
    symbol: '🖥️',
    color: '#6F422B',
  },
  {
    id: 'desk-sage',
    name: '세이지 책상',
    description: '차분한 세이지색 서랍 책상',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 460,
    symbol: '🖥️',
    color: '#9EAA82',
  },
  {
    id: 'desk-rattan',
    name: '라탄 책상',
    description: '크림색 나무와 라탄 서랍',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 580,
    symbol: '🖥️',
    color: '#E5C895',
  },
  {
    id: 'chair-cushion',
    name: '쿠션 의자',
    description: '오래 앉아도 포근해요',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 220,
    symbol: '🪑',
    color: '#D7B99A',
    isDefault: true,
    gridSize: { columns: 2, rows: 2 },
  },
  {
    id: 'cabinet-low',
    name: '낮은 원목 수납장',
    description: '책과 소품을 가지런히',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 380,
    symbol: '🗄️',
    color: '#E9C58D',
    gridSize: { columns: 6, rows: 2 },
  },
  {
    id: 'chair-mint',
    name: '민트 의자',
    description: '폭신한 민트 쿠션',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 240,
    symbol: '🪑',
    color: '#B9D8C8',
  },
  {
    id: 'chair-walnut',
    name: '월넛 의자',
    description: '짙은 원목과 크림 쿠션',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 320,
    symbol: '🪑',
    color: '#74442F',
  },
  {
    id: 'chair-lavender',
    name: '라벤더 의자',
    description: '꽃무늬 등받이와 부드러운 색감',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 340,
    symbol: '🪑',
    color: '#C8A9DB',
  },
  {
    id: 'chair-rattan-blue',
    name: '블루 라탄 의자',
    description: '라탄 등받이와 푸른 쿠션',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 390,
    symbol: '🪑',
    color: '#AFC8D8',
  },
  {
    id: 'shelf-basic',
    name: '작은 벽 선반',
    description: '책 몇 권을 올린 기본 선반',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 0,
    symbol: '📚',
    color: '#D6AD79',
    isDefault: true,
  },
  {
    id: 'shelf-walnut',
    name: '월넛 벽 선반',
    description: '짙은 원목과 고전적인 책 세 권',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 280,
    symbol: '📚',
    color: '#70442F',
  },
  {
    id: 'shelf-cream',
    name: '크림 벽 선반',
    description: '밝은 원목과 복숭아빛 책',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 260,
    symbol: '📚',
    color: '#E7D2AB',
  },
  {
    id: 'shelf-sage',
    name: '세이지 벽 선반',
    description: '나무 상판과 세이지색 받침',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 300,
    symbol: '📚',
    color: '#A7AD7D',
  },
  {
    id: 'shelf-navy',
    name: '네이비 벽 선반',
    description: '차분한 남색과 월넛 테두리',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 340,
    symbol: '📚',
    color: '#596B8C',
  },
  {
    id: 'rug-round',
    name: '크림 원형 러그',
    description: '빈 바닥을 포근하게 채워요',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 180,
    symbol: '⭕',
    color: '#F4E4CF',
  },
  {
    id: 'rug-mint-braid',
    name: '민트 브레이드 러그',
    description: '포근한 민트색 타원 러그',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 240,
    symbol: '🟢',
    color: '#BFDCC4',
  },
  {
    id: 'rug-rose-floral',
    name: '로즈 플라워 러그',
    description: '작은 꽃이 수놓인 사각 러그',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 280,
    symbol: '🌸',
    color: '#E7A49B',
  },
  {
    id: 'rug-sky-cloud',
    name: '하늘 구름 러그',
    description: '폭신한 구름 모양 러그',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 320,
    symbol: '☁️',
    color: '#A8DDF2',
  },
  {
    id: 'rug-sun',
    name: '햇살 러그',
    description: '방을 환하게 만드는 둥근 러그',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 340,
    symbol: '☀️',
    color: '#F6C454',
  },
  {
    id: 'curtain-linen',
    name: '린넨 커튼',
    description: '창가에 부드러운 빛을 더해요',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 220,
    symbol: '🪟',
    color: '#F1DFBF',
  },
  {
    id: 'curtain-sage',
    name: '세이지 커튼',
    description: '차분한 초록빛 창가',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 260,
    symbol: '🪟',
    color: '#A9BA82',
  },
  {
    id: 'curtain-rose',
    name: '로즈 플라워 커튼',
    description: '작은 꽃무늬가 있는 장밋빛 커튼',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 300,
    symbol: '🪟',
    color: '#D78E91',
  },
  {
    id: 'curtain-sky',
    name: '하늘 체크 커튼',
    description: '산뜻한 하늘색 체크무늬',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 320,
    symbol: '🪟',
    color: '#A8C8E7',
  },
  {
    id: 'curtain-lavender',
    name: '별빛 라벤더 커튼',
    description: '별이 수놓인 라벤더 커튼',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 340,
    symbol: '🪟',
    color: '#C4A0DE',
  },
  {
    id: 'bookcase-small',
    name: '작은 책장',
    description: '책상 옆을 차분하게 채워요',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 300,
    symbol: '📚',
    color: '#C89761',
  },
  {
    id: 'bookcase-cream',
    name: '크림 서랍 책장',
    description: '둥근 모서리와 작은 서랍',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 360,
    symbol: '📚',
    color: '#E9D7AE',
  },
  {
    id: 'bookcase-sage',
    name: '세이지 바구니 책장',
    description: '원목 상판과 작은 수납 바구니',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 380,
    symbol: '📚',
    color: '#8F9C67',
  },
  {
    id: 'bookcase-walnut',
    name: '월넛 클래식 책장',
    description: '고전적인 짙은 원목 책장',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 420,
    symbol: '📚',
    color: '#75452C',
  },
  {
    id: 'bookcase-sky',
    name: '하늘빛 책장',
    description: '하얀 테두리의 산뜻한 책장',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 400,
    symbol: '📚',
    color: '#A9CDE2',
  },
  {
    id: 'coffee-mug',
    name: '따뜻한 커피',
    description: '책상 위 작은 휴식',
    category: 'coffee',
    slot: 'roomCoffee',
    price: 100,
    symbol: '☕',
    color: '#C9956B',
    gridSize: { columns: 2, rows: 2 },
  },
  {
    id: 'coffee-dessert',
    name: '마카롱 라테 세트',
    description: '달콤한 오후의 한 잔',
    category: 'coffee',
    slot: 'roomCoffee',
    price: 180,
    symbol: '☕',
    color: '#F7D6B8',
    gridSize: { columns: 3, rows: 2 },
  },
  {
    id: 'plant-pothos',
    name: '포토스 화분',
    description: '창가의 초록 친구',
    category: 'plant',
    slot: 'roomPlant',
    price: 150,
    symbol: '🪴',
    color: '#79A873',
    isDefault: true,
    gridSize: { columns: 1, rows: 1 },
  },
  {
    id: 'plant-monstera',
    name: '몬스테라 화분',
    description: '방을 채우는 싱그러운 잎',
    category: 'plant',
    slot: 'roomPlant',
    price: 260,
    symbol: '🌿',
    color: '#B8CC79',
    gridSize: { columns: 4, rows: 5 },
  },
  {
    id: 'plant-olive',
    name: '올리브 화분',
    description: '차분한 올리브 나무',
    category: 'plant',
    slot: 'roomPlant',
    price: 280,
    symbol: '🪴',
    color: '#A8B47C',
  },
  {
    id: 'pet-cat',
    name: '창가 고양이',
    description: '꼬리를 살랑이는 친구',
    category: 'pet',
    slot: 'roomPet',
    price: 500,
    symbol: '🐈',
    color: '#D6A36F',
    gridSize: { columns: 4, rows: 3 },
  },
  {
    id: 'pet-dog',
    name: '포근한 강아지',
    description: '고개를 갸웃하는 작은 친구',
    category: 'pet',
    slot: 'roomPet',
    price: 650,
    symbol: '🐶',
    color: '#EDC47C',
    gridSize: { columns: 4, rows: 3 },
  },
  {
    id: 'bed-rose',
    name: '로즈 침대',
    description: '차분한 장밋빛 침구',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 480,
    symbol: '🛏️',
    color: '#E9B4AE',
  },
  {
    id: 'bed-sky',
    name: '하늘 침대',
    description: '맑은 하늘빛 침구',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 480,
    symbol: '🛏️',
    color: '#C8DDF0',
  },
  {
    id: 'bed-princess',
    name: '공주님 캐노피 침대',
    description: '리본과 캐노피가 있는 특별한 침대',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 900,
    symbol: '🛏️',
    color: '#F5D4D4',
  },
  {
    id: 'bed-canopy-lavender',
    name: '라벤더 캐노피 침대',
    description: '차분한 라벤더빛 커튼이 감싸는 침대',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 980,
    symbol: '🛏️',
    color: '#C9AFE8',
  },
  {
    id: 'bed-sleigh-navy',
    name: '딥블루 슬레이 침대',
    description: '곡선 원목과 짙은 남색 침구의 클래식 침대',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 760,
    symbol: '🛏️',
    color: '#243C69',
  },
  {
    id: 'bed-iron-sage',
    name: '세이지 철제 침대',
    description: '식물 무늬 프레임이 돋보이는 가벼운 침대',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 680,
    symbol: '🛏️',
    color: '#A8AD72',
  },
  {
    id: 'bed-upholstered-wine',
    name: '와인 패브릭 침대',
    description: '부드러운 버튼 장식 패브릭 침대',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 820,
    symbol: '🛏️',
    color: '#9F3F4D',
  },
  {
    id: 'wall-calendar',
    name: '포근한 달력',
    description: '벽에 거는 작은 달력',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 160,
    symbol: '📅',
    color: '#E7DEC1',
  },
  {
    id: 'wall-poster',
    name: '보태니컬 포스터',
    description: '초록 잎이 담긴 원목 액자',
    category: 'furniture',
    slot: 'roomFurniture',
    price: 200,
    symbol: '🖼️',
    color: '#DDE6C7',
  },
  {
    id: 'drink-coffee',
    name: '따뜻한 커피',
    description: '책상 위 김이 오르는 한 잔',
    category: 'coffee',
    slot: 'roomCoffee',
    price: 100,
    symbol: '☕',
    color: '#D6B18C',
  },
  {
    id: 'drink-beer',
    name: '시원한 캔맥주',
    description: '하루 끝의 작은 휴식',
    category: 'coffee',
    slot: 'roomCoffee',
    price: 140,
    symbol: '🥫',
    color: '#E9C76B',
  },
  {
    id: 'drink-barley',
    name: '얼음 보리차',
    description: '구수하고 시원한 보리차',
    category: 'coffee',
    slot: 'roomCoffee',
    price: 120,
    symbol: '🥃',
    color: '#DDA85D',
  },
  {
    id: 'plant-succulent',
    name: '다육이 화분',
    description: '책상과 선반에 어울리는 작은 식물',
    category: 'plant',
    slot: 'roomPlant',
    price: 180,
    symbol: '🪴',
    color: '#A9BD70',
  },
  {
    id: 'plant-fern',
    name: '풍성한 고사리',
    description: '넓게 퍼지는 싱그러운 잎',
    category: 'plant',
    slot: 'roomPlant',
    price: 340,
    symbol: '🌿',
    color: '#86A85D',
  },
  {
    id: 'plant-fiddle',
    name: '키 큰 떡갈고무나무',
    description: '바닥을 채우는 키 큰 식물',
    category: 'plant',
    slot: 'roomPlant',
    price: 420,
    symbol: '🪴',
    color: '#75934F',
  },
  {
    id: 'pet-cat-gray',
    name: '회색 줄무늬 고양이',
    description: '같은 장난을 즐기는 다른 털빛 친구',
    category: 'pet',
    slot: 'roomPet',
    price: 550,
    symbol: '🐈',
    color: '#C9C5BF',
  },
  {
    id: 'pet-dog-brown',
    name: '초콜릿 강아지',
    description: '포근한 갈색 털의 작은 친구',
    category: 'pet',
    slot: 'roomPet',
    price: 700,
    symbol: '🐶',
    color: '#B77B50',
  },
];

export const DEFAULT_DECORATION_IDS = SHOP_ITEMS.filter(
  (item) => item.isDefault,
).map((item) => item.id);
