import type { Route as _IndexRoute } from '../pages/';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _CheckInRoute } from '../pages/check-in';
import type { Route as _DiaryStyleRoute } from '../pages/diary-style';
import type { Route as _MonthlyJournalRoute } from '../pages/monthly-journal';
import type { Route as _RecordDetailRoute } from '../pages/record-detail';
import type { Route as _RecordsRoute } from '../pages/records';
import type { Route as _ResultRoute } from '../pages/result';
import type { Route as _RewardsRoute } from '../pages/rewards';
import type { Route as _RoomRoute } from '../pages/room';
import type { Route as _ShopRoute } from '../pages/shop';
import type { Route as _StatisticsRoute } from '../pages/statistics';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/check-in': (typeof _CheckInRoute)['_inputType'];
    '/diary-style': (typeof _DiaryStyleRoute)['_inputType'];
    '/monthly-journal': (typeof _MonthlyJournalRoute)['_inputType'];
    '/record-detail': (typeof _RecordDetailRoute)['_inputType'];
    '/records': (typeof _RecordsRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
    '/rewards': (typeof _RewardsRoute)['_inputType'];
    '/room': (typeof _RoomRoute)['_inputType'];
    '/shop': (typeof _ShopRoute)['_inputType'];
    '/statistics': (typeof _StatisticsRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/check-in': (typeof _CheckInRoute)['_outputType'];
    '/diary-style': (typeof _DiaryStyleRoute)['_outputType'];
    '/monthly-journal': (typeof _MonthlyJournalRoute)['_outputType'];
    '/record-detail': (typeof _RecordDetailRoute)['_outputType'];
    '/records': (typeof _RecordsRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
    '/rewards': (typeof _RewardsRoute)['_outputType'];
    '/room': (typeof _RoomRoute)['_outputType'];
    '/shop': (typeof _ShopRoute)['_outputType'];
    '/statistics': (typeof _StatisticsRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
